#
@PARAM
IF=(FN=%INDATA%FIDX_30,ORG=I)
OF=(FN=%OTDATA%TEMP_SEQ,ORG=S,RECL=30)
@PEND
\BJ_FUTIL
@PARAM
IF=(FN=%OTDATA%TEMP_SEQ,ORG=S)
OF=(FN=%OTDATA%CSET_OF_SEQ,ORG=S,RECL=30)
@PEND
\BJ_FUTIL
@SET QUTESTID  'CSET_OF_SEQ'
@INSERT jcl\QU_INSERT30.txt
>end
