＃OFのRECL指定が優先される
@PARAM
IF=(FN=%INDATA%FSEQ_10,ORG=S)
OF=(FN=%OTDATA%OF_RECL_SEQ05,ORG=S,RECL=10)
@PEND
\BJ_FUTIL
@PARAM
IF=(FN=%INDATA%FSEQ_10,ORG=S)
OF=(FN=%OTDATA%OF_RECL_SEQ05,ORG=S,RECL=5)
@PEND
\BJ_FUTIL
@SET QUTESTID  'OF_RECL_SEQ05'
@INSERT jcl\QU_INSERT_T.txt
>end
