set CLASSPATH=%CLASSPATH%;../BJTOOL_IS/jar/bjtool.jar
call 00_runJcl AC4_ARRANGE_CHAR
call 00_runJcl AC4_ARRANGE_FBIN
call 00_runJcl AC4_ARRANGE_HEX
call 00_runJcl AC4_ARRANGE_NCHR
call 00_runJcl AC4_ARRANGE_PDEC
call 00_runJcl AC4_ARRANGE_SBIN
call 00_runJcl AC4_ARRANGE_UBIN
call 00_runJcl AC4_ARRANGE_UDEC
call 00_runJcl AC4_INC_AND_AND
call 00_runJcl AC4_INC_AND_OR
call 00_runJcl AC4_INC_CHAR_EQ
call 00_runJcl AC4_INC_CHAR_EQ2
call 00_runJcl AC4_INC_CHAR_GE
call 00_runJcl AC4_INC_CHAR_GT
call 00_runJcl AC4_INC_CHAR_HEX
call 00_runJcl AC4_INC_CHAR_LE
call 00_runJcl AC4_INC_CHAR_LT
call 00_runJcl AC4_INC_CHAR_NE
call 00_runJcl AC4_INC_FBIN_GT
call 00_runJcl AC4_INC_NCHR_EQ
call 00_runJcl AC4_INC_UDEC_EQ
call 00_runJcl AC4_INC_UDEC_NEG
call 00_runJcl AC4_INC_UDEC_POS
call 00_runJcl AC4_INC_UDEC_ZERO
call 00_runJcl AC4_OMIT_SBIN_LE
call 00_runJcl AC4_OMIT_UBIN_GE