@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,ORG=S,RECL=40)
OF=(FN=%OTDATA%AC4_INC_AND_AND,ORG=S,RECL=40)
INCLUDE=(1 3 GT CHAR "060")AND(1 3 LT CHAR "130")AND(4 2 NE CHAR "EE")
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_INC_AND_AND'
@INSERT jcl\QU_INSERT.txt
