\BJ_FDEL  %OTDATA%FUTIL_CRE_001
@PARAM
IF=(FN=%INDATA%FSEQ_10,RECL=10)
OF=(FN=%OTDATA%FUTIL_CRE_001,RECL=10)
@PEND
\BJ_FLCNV CRE
@SET QUTESTID  'FUTIL_CRE_001'
@SET QUFNAME1  '%OTDATA%FUTIL_CRE_001'
@SET QUFNAME2  '%CTDATA%FUTIL_CRE_001'
\QUCOMP
