@PARAM
IF=(FN=%INDATA%FSEQ_10,RECL=10)
OF=(FN=%OTDATA%FUTIL_ADD_001,RECL=10)
@PEND
\BJ_FUTIL
@PARAM
IF=(FN=%INDATA%FSEQ_10,RECL=10)
OF=(FN=%OTDATA%FUTIL_ADD_001,RECL=10)
@PEND
\BJ_FUTIL ADD
@SET QUTESTID  'FUTIL_ADD_001'
@SET QUFNAME1  '%OTDATA%FUTIL_ADD_001'
@SET QUFNAME2  '%CTDATA%FUTIL_ADD_001'
\QUCOMP
