@DISPLAY ***** INSERT ƒeƒXƒg *************
@INSERT  JCL\INSERT_001INS.jcl
@SET QUTESTID  'INSERT_001'
@SET QUFNAME1  '%OLOG%&QUTESTID&.log'
@SET QUFNAME2  '%CLOG%&QUTESTID&.log'
\QUCOMPLOG 0003:0003
@END
