@SET BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,RECL=40)
OF=(FN=%OTDATA%AC4_KEY1_SUM_P,RECL=40)
KEY=(4,2,CHAR)
SUM=(21,5,PDEC)
@PEND
\BJ_SORT
@SET QUTESTID  'AC4_KEY1_SUM_P'
@INSERT jcl\QU_INSERT.txt
