@SET BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,RECL=40)
OF=(FN=%OTDATA%AC4_KEY1_SUM_S,RECL=40)
KEY=(4,2,CHAR)
SUM=(7,5,UDEC)
@PEND
\BJ_SORT
@SET QUTESTID  'AC4_KEY1_SUM_S'
@INSERT jcl\QU_INSERT.txt
