@SET BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,RECL=40)
OF=(FN=%OTDATA%AC4_KEY1_SUM_B4,RECL=40)
KEY=(4,2,CHAR)
SUM=(16,4,SBIN)
@PEND
\BJ_SORT
@SET QUTESTID  'AC4_KEY1_SUM_B4'
@INSERT jcl\QU_INSERT.txt
