
@SET BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,RECL=40)
OF=(FN=%OTDATA%AC4_KEY1_INC_AND3,RECL=40)
INC=((4,2,GE,"FF")AND(4,2,GE,"PP")AND(7,5,GT,UDEC,0))
KEY=(4,2,CHAR)
@PEND
\BJ_SORT
@SET QUTESTID  'AC4_KEY1_INC_AND3'
@INSERT jcl\QU_INSERT.txt

