       SELECT QUTESTF
           ASSIGN       TO  "data\QUTESTF"
           ORGANIZATION IS INDEXED
           ACCESS MODE  IS DYNAMIC
           FILE STATUS  IS FILE-STS
           RECORD KEY   IS QU-KEY1.
