@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,ORG=SEQ,RECL=40)
OF=(FN=%OTDATA%AC4_OMIT_SBIN_LE,RECL=40)
OMIT=(16,4,LE,SBIN,-30)
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_OMIT_SBIN_LE'
@INSERT jcl\QU_INSERT.txt