@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,ORG=S,RECL=40)
OF=(FN=%OTDATA%AC4_INC_CHAR_HEX,RECL=40)
 INCLUDE=(1,3,GE,H'313830')
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_INC_CHAR_HEX'
@INSERT jcl\QU_INSERT.txt
