@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,RECL=40)
OF=(FN=%OTDATA%AC4_INC_FBIN_GT,RECL=40)
INCLUDE=(27,4,GT,FBIN,511.5)
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_INC_FBIN_GT'
@INSERT jcl\QU_INSERT.txt
