@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,ORG=S,RECL=40)
OF=(FN=%OTDATA%AC4_INC_AND_OR,ORG=S,RECL=40)
INCLUDE=((1,3,EQ,CHAR,'010') OR (2,2,EQ,CHAR,'00') AND (21,5,EQ,PDEC,-708027))
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_INC_AND_OR'
@INSERT jcl\QU_INSERT.txt