@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,RECL=40)
OF=(FN=%OTDATA%AC4_INC_UDEC_EQ,RECL=40)
INCLUDE=(7,5,EQ,UDEC,'-435')
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_INC_UDEC_EQ'
@INSERT jcl\QU_INSERT.txt