@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FTXT_20,ORG=T,RECL=20)
OF=(FN=%OTDATA%AC4_INC_NCHR_EQ,ORG=T,RECL=20)
INCLUDE=(13,8,EQ,NCHR,'‚«‚­‚¯‚±')
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_INC_NCHR_EQ'
@INSERT jcl\QU_INSERT_T.txt
