@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,ORG=S,RECL=40)
OF=(FN=%OTDATA%AC4_ARRANGE_NCHR,ORG=T,RECL=50)
ARRANGE=((1 3)(" ")(4 2)(4 NCHR "Žõˆê")(5 CHAR "´ËÞ»Ü")(7 5))
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_ARRANGE_NCHR'
@INSERT jcl\QU_INSERT_T.txt
