@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,ORG=S,RECL=40)
OF=(FN=%OTDATA%AC4_INC_CHAR_NE,ORG=T,RECL=40)
INCLUDE=(4 2 NE CHAR "EE")
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_INC_CHAR_NE'
@SET QUFNAME1  '%OTDATA%AC4_INC_CHAR_NE'
@SET QUFNAME2  '%CTDATA%AC4_INC_CHAR_NE'
\QUCOMP
