@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,ORG=S,RECL=40)
OF=(FN=%OTDATA%AC4_ARRANGE_UBIN,ORG=T,RECL=15)
ARRANGE=((1 3)(" ")(4 2)(2 UBIN "11")(7 5))
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_ARRANGE_UBIN'
@INSERT jcl\QU_INSERT_T.txt
