@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,ORG=S,RECL=40)
OF=(FN=%OTDATA%AC4_ARRANGE_HEX,ORG=T,RECL=20)
ARRANGE=((1 3)(" ")(4 2)(3 HEX H"313339")(7 5))
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_ARRANGE_HEX'
@INSERT jcl\QU_INSERT_T.txt