@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,ORG=SEQ,RECL=40)
OF=(FN=%OTDATA%AC4_INC_UBIN_GE,RECL=40)
 OMIT=(13,2,GE,UBIN,100)
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_INC_UBIN_GE'
@INSERT jcl\QU_INSERT.txt