@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,ORG=S,RECL=40)
OF=(FN=%OTDATA%AC4_INC_UDEC_ZERO,RECL=40)
INCLUDE=(2,2,ZERO,UDEC)
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_INC_UDEC_ZERO'
@INSERT jcl\QU_INSERT.txt
