@SET    BJ_FUTIL_PARAOPT 'AC4'
@PARAM
IF=(FN=%INDATA%FSEQ_40,RECL=40)
OF=(FN=%OTDATA%AC4_INC_CHAR_EQ2,RECL=40)
INCLUDE=(1 3 EQ CHAR H"303830")
@PEND
\BJ_FLCNV
@SET QUTESTID  'AC4_INC_CHAR_EQ2'
@INSERT jcl\QU_INSERT.txt
