@PARAM
IF=(FN=%INDATA%FSEQ_40,RECL=40)
OF=(FN=%OTDATA%AVX_SEL_AND_AND,RECL=40)
SEL=((4,2,C,EQ,@EE@)AND(7,5,S,GT,@0@)A(21,5,P,GT,@500000@))
@PEND
\BJ_FLCNV
@SET QUTESTID  'AVX_SEL_AND_AND'
@INSERT jcl\QU_INSERT.txt
