@PARAM
IF=(FN=%INDATA%FIDX_40,ORG=I)
OF=(FN=%OTDATA%AVX_OUT_001,ORG=T,RECL=1,50)
OUT=((@PKEY=@),(1,3),(@ A-KEY=@),(4,2),(@ A-1=@),(7,5),(@***@))
@PEND
\BJ_FLCNV
@SET QUTESTID  'AVX_OUT_001'
@SET QUFNAME1  '%OTDATA%AVX_OUT_001'
@SET QUFNAME2  '%CTDATA%AVX_OUT_001'
\QUCOMP
