@SET    BJ_FUTIL_PARAOPT 'MSP'
@PARAM
IF=(FN=%INDATA%FSEQ_40,RECL=40)
OF=(FN=%OTDATA%MVS_OMIT_CH_LT,ORG=S,RECL=40)
  OMIT COND=(4,2,CH,LT,C'LL')
@PEND
\BJ_FLCNV
@SET QUTESTID  'MVS_OMIT_CH_LT'
@INSERT jcl\QU_INSERT.txt
