@SET BJ_FUTIL_PARAOPT 'MSP'
@PARAM
IF=(FN=%INDATA%FSEQ_40,RECL=40)
OF=(FID=F1,FN=%OTDATA%MVS_OUTF2_001A,RECL=40)
OF=(FID=F2,FN=%OTDATA%MVS_OUTF2_001B,RECL=40)
 OUTFIL FILES=F1,INCLUDE=ALL
 OUTFIL FILES=F2,INCLUDE=(4,2,CH,EQ,C'AA',OR,7,5,ZD,EQ,475)
@PEND
\BJ_FLCNV
@SET QUTESTID  'MVS_OUTF2_001A'
@INSERT jcl\QU_INSERT.txt
@SET QUTESTID  'MVS_OUTF2_001B'
@INSERT jcl\QU_INSERT.txt
