@SET    BJ_FUTIL_PARAOPT 'MSP'
@PARAM
IF=(FN=%INDATA%FSEQ_40,RECL=40)
OF=(FN=%OTDATA%MVS_OMIT_ZD_LE,ORG=S,RECL=40)
 OMIT COND=(7,5,ZD,LE,-525)
@PEND
\BJ_FLCNV
@SET QUTESTID  'MVS_OMIT_ZD_LE'
@INSERT jcl\QU_INSERT.txt
