@SET    BJ_FUTIL_PARAOPT 'MSP'
@PARAM
IF=(FN=%INDATA%FSEQ_40,ORG=S,RECL=40)
OF=(FN=%OTDATA%MVS_OMIT_CH_GE,ORG=S,RECL=40)
 OMIT COND=(1,3,CH,GE,X'313030')
@PEND
\BJ_FLCNV
@SET QUTESTID  'MVS_OMIT_CH_GE'
@INSERT jcl\QU_INSERT.txt
